//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_table
    {
        public int address_id { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string neighbourhood { get; set; }
        public string street { get; set; }
        public string building_no { get; set; }
        public int user_id { get; set; }
    
        public virtual users_table users_table { get; set; }
    }
}
