//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adverts_table
    {
        public int advert_id { get; set; }
        public int help_type_id { get; set; }
    
        public virtual help_type_table help_type_table { get; set; }
    }
}
