//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class welfareDBEntities : DbContext
    {
        public welfareDBEntities()
            : base("name=welfareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address_table> address_table { get; set; }
        public virtual DbSet<adverts_table> adverts_table { get; set; }
        public virtual DbSet<blood_donation_table> blood_donation_table { get; set; }
        public virtual DbSet<business_help_table> business_help_table { get; set; }
        public virtual DbSet<clothes_table> clothes_table { get; set; }
        public virtual DbSet<education_table> education_table { get; set; }
        public virtual DbSet<events_table> events_table { get; set; }
        public virtual DbSet<financial_support_table> financial_support_table { get; set; }
        public virtual DbSet<help_type_table> help_type_table { get; set; }
        public virtual DbSet<shelter_table> shelter_table { get; set; }
        public virtual DbSet<stationary_table> stationary_table { get; set; }
        public virtual DbSet<street_animal_table> street_animal_table { get; set; }
        public virtual DbSet<supply_table> supply_table { get; set; }
        public virtual DbSet<user_role_mapping> user_role_mapping { get; set; }
        public virtual DbSet<user_type_table> user_type_table { get; set; }
        public virtual DbSet<users_table> users_table { get; set; }
    }
}
