//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role_mapping
    {
        public int id { get; set; }
        public int user_type_id { get; set; }
        public int user_id { get; set; }
    
        public virtual user_type_table user_type_table { get; set; }
        public virtual users_table users_table { get; set; }
    }
}
